"""seed_kb_permissions

Revision ID: 0e8a8e1e2221
Revises: 53b0ae807569
Create Date: 2026-08-05 00:53:32.320896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e8a8e1e2221'
down_revision: Union[str, Sequence[str], None] = '53b0ae807569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    
    import uuid
    from datetime import datetime
    
    permissions = sa.table(
        'permissions',
        sa.column('id', sa.UUID(as_uuid=True)),
        sa.column('codename', sa.String),
        sa.column('display_name', sa.String),
        sa.column('description', sa.Text),
        sa.column('module', sa.String),
        sa.column('created_at', sa.DateTime),
    )

    new_permissions = [
        {
            "id": uuid.uuid4(),
            "codename": "create_kb_articles",
            "display_name": "Create KB Articles",
            "module": "Knowledge",
            "description": "Create new knowledge base articles",
            "created_at": datetime.utcnow()
        },
        {
            "id": uuid.uuid4(),
            "codename": "edit_kb_articles",
            "display_name": "Edit KB Articles",
            "module": "Knowledge",
            "description": "Edit existing knowledge base articles",
            "created_at": datetime.utcnow()
        },
        {
            "id": uuid.uuid4(),
            "codename": "publish_kb_articles",
            "display_name": "Publish KB Articles",
            "module": "Knowledge",
            "description": "Review and publish knowledge base articles",
            "created_at": datetime.utcnow()
        },
        {
            "id": uuid.uuid4(),
            "codename": "delete_kb_articles",
            "display_name": "Delete KB Articles",
            "module": "Knowledge",
            "description": "Archive or permanently delete knowledge base articles",
            "created_at": datetime.utcnow()
        }
    ]

    for p in new_permissions:
        op.execute(f"INSERT INTO permissions (id, codename, display_name, description, module, created_at) VALUES ('{p['id']}', '{p['codename']}', '{p['display_name']}', '{p['description']}', '{p['module']}', '{p['created_at']}') ON CONFLICT (codename) DO NOTHING")


def downgrade() -> None:
    """Downgrade schema."""
    pass
