"""add_auth_and_user_management_tables

Revision ID: 35c2593f1959
Revises: f75f1deac5b0
Create Date: 2026-08-02 23:26:46.400046

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "35c2593f1959"
down_revision: Union[str, Sequence[str], None] = "f75f1deac5b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure postgresql enum authtokentype is created safely
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        postgresql.ENUM("EMAIL_VERIFICATION", "PASSWORD_RESET", name="authtokentype").create(
            bind, checkfirst=True
        )
        # Add new enum values to actiontype
        for val in [
            "SIGNUP",
            "LOGIN",
            "LOGOUT",
            "PASSWORD_CHANGE",
            "PASSWORD_RESET",
            "EMAIL_VERIFY",
            "PROFILE_UPDATE",
            "AVATAR_CHANGE",
        ]:
            op.execute(sa.text(f"ALTER TYPE actiontype ADD VALUE IF NOT EXISTS '{val}'"))

    op.create_table(
        "auth_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "token_type",
            postgresql.ENUM(
                "EMAIL_VERIFICATION", "PASSWORD_RESET", name="authtokentype", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index("ix_auth_token_hash", "auth_tokens", ["token_hash"], unique=False)
    op.create_index("ix_auth_token_user", "auth_tokens", ["user_id"], unique=False)
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=255), nullable=False),
        sa.Column("device_info", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=50), nullable=True),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("refresh_token_hash"),
    )
    op.create_index("ix_session_org", "user_sessions", ["organization_id"], unique=False)
    op.create_index("ix_session_user", "user_sessions", ["user_id"], unique=False)
    op.add_column("users", sa.Column("display_name", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("avatar_url", sa.String(length=1024), nullable=True))
    op.add_column("users", sa.Column("job_title", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("bio", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("timezone", sa.String(length=50), nullable=False))
    op.add_column("users", sa.Column("preferred_language", sa.String(length=10), nullable=False))
    op.add_column("users", sa.Column("theme_preference", sa.String(length=20), nullable=False))
    op.add_column(
        "users",
        sa.Column(
            "notification_preferences",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
    )
    op.add_column("users", sa.Column("is_email_verified", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("last_login_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("last_active_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("failed_login_attempts", sa.Integer(), nullable=False))
    op.add_column("users", sa.Column("locked_until", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "locked_until")
    op.drop_column("users", "failed_login_attempts")
    op.drop_column("users", "last_active_at")
    op.drop_column("users", "last_login_at")
    op.drop_column("users", "is_email_verified")
    op.drop_column("users", "notification_preferences")
    op.drop_column("users", "theme_preference")
    op.drop_column("users", "preferred_language")
    op.drop_column("users", "timezone")
    op.drop_column("users", "bio")
    op.drop_column("users", "job_title")
    op.drop_column("users", "avatar_url")
    op.drop_column("users", "display_name")
    op.drop_index("ix_session_user", table_name="user_sessions")
    op.drop_index("ix_session_org", table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index("ix_auth_token_user", table_name="auth_tokens")
    op.drop_index("ix_auth_token_hash", table_name="auth_tokens")
    op.drop_table("auth_tokens")
    # ### end Alembic commands ###
