"""add_enterprise_team_management

Revision ID: 52897686fa4b
Revises: e4bead1f74b7
Create Date: 2026-08-03 12:48:41.583396

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "52897686fa4b"
down_revision: Union[str, Sequence[str], None] = "e4bead1f74b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skills",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "TECHNICAL",
                "PRODUCT",
                "BILLING",
                "SALES",
                "SOFT_SKILL",
                "OTHER",
                name="skillcategory",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_skill_org_name"),
    )
    op.create_index("ix_skill_organization", "skills", ["organization_id"], unique=False)
    op.create_table(
        "agent_availabilities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "AVAILABLE",
                "BUSY",
                "AWAY",
                "OFFLINE",
                "BREAK",
                "MEETING",
                "TRAINING",
                "VACATION",
                "SICK_LEAVE",
                name="agentstatus",
            ),
            nullable=False,
        ),
        sa.Column("since", sa.DateTime(), nullable=False),
        sa.Column("expected_return", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "agent_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("agent_code", sa.String(length=50), nullable=True),
        sa.Column("employee_id", sa.String(length=100), nullable=True),
        sa.Column(
            "experience_level",
            sa.Enum("BEGINNER", "INTERMEDIATE", "ADVANCED", "EXPERT", name="proficiencylevel"),
            nullable=True,
        ),
        sa.Column(
            "languages_spoken",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("max_concurrent_tickets", sa.Integer(), nullable=False),
        sa.Column("current_active_tickets", sa.Integer(), nullable=False),
        sa.Column("max_daily_tickets", sa.Integer(), nullable=False),
        sa.Column("current_daily_tickets", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "agent_skills",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column(
            "proficiency_level",
            sa.Enum("BEGINNER", "INTERMEDIATE", "ADVANCED", "EXPERT", name="proficiencylevel"),
            nullable=False,
        ),
        sa.Column("years_of_experience", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "skill_id", name="uq_agent_skill"),
    )
    op.create_table(
        "departments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ARCHIVED", "DELETED", name="departmentstatus"),
            nullable=False,
        ),
        sa.Column("manager_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["manager_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_organization_department_name"),
    )
    op.create_index("ix_department_organization", "departments", ["organization_id"], unique=False)
    op.create_table(
        "working_hours",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column(
            "shifts",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "working_days",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("start_time", sa.String(length=5), nullable=False),
        sa.Column("end_time", sa.String(length=5), nullable=False),
        sa.Column("lunch_break_start", sa.String(length=5), nullable=True),
        sa.Column("lunch_break_end", sa.String(length=5), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.add_column("team_members", sa.Column("id", sa.UUID(), nullable=False))
    op.add_column("team_members", sa.Column("is_primary", sa.Boolean(), nullable=False))
    op.add_column("team_members", sa.Column("joined_at", sa.DateTime(), nullable=True))
    op.create_index("ix_teammember_team", "team_members", ["team_id"], unique=False)
    op.create_index("ix_teammember_user", "team_members", ["user_id"], unique=False)
    op.create_unique_constraint("uq_team_user", "team_members", ["team_id", "user_id"])
    op.add_column("teams", sa.Column("department_id", sa.UUID(), nullable=True))
    op.add_column("teams", sa.Column("avatar_url", sa.String(length=1024), nullable=True))
    op.add_column("teams", sa.Column("color", sa.String(length=7), nullable=True))
    # Create ENUM type manually for PostgreSQL before using in add_column
    team_status_enum = postgresql.ENUM("ACTIVE", "ARCHIVED", "DELETED", name="teamstatus")
    team_status_enum.create(op.get_bind())

    op.add_column(
        "teams",
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ARCHIVED", "DELETED", name="teamstatus"),
            nullable=False,
            server_default="ACTIVE",
        ),
    )
    op.add_column(
        "teams", sa.Column("max_capacity", sa.Integer(), nullable=False, server_default="50")
    )
    op.add_column(
        "teams", sa.Column("current_capacity", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column("teams", sa.Column("default_sla", sa.Integer(), nullable=True))
    op.add_column(
        "teams",
        sa.Column(
            "business_hours",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        None, "teams", "departments", ["department_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "teams", type_="foreignkey")
    op.drop_column("teams", "business_hours")
    op.drop_column("teams", "default_sla")
    op.drop_column("teams", "current_capacity")
    op.drop_column("teams", "max_capacity")
    op.drop_column("teams", "status")
    op.drop_column("teams", "color")
    op.drop_column("teams", "avatar_url")
    op.drop_column("teams", "department_id")
    op.drop_constraint("uq_team_user", "team_members", type_="unique")
    op.drop_index("ix_teammember_user", table_name="team_members")
    op.drop_index("ix_teammember_team", table_name="team_members")
    op.drop_column("team_members", "joined_at")
    op.drop_column("team_members", "is_primary")
    op.drop_column("team_members", "id")
    op.drop_table("working_hours")
    op.drop_index("ix_department_organization", table_name="departments")
    op.drop_table("departments")
    op.drop_table("agent_skills")
    op.drop_table("agent_profiles")
    op.drop_table("agent_availabilities")
    op.drop_index("ix_skill_organization", table_name="skills")
    op.drop_table("skills")
    # ### end Alembic commands ###
