"""add_kb_engine_tables

Revision ID: 53b0ae807569
Revises: a17473f40aba
Create Date: 2026-08-05 00:51:55.800295

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "53b0ae807569"
down_revision: Union[str, Sequence[str], None] = "a17473f40aba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Handle Enums explicitly for PostgreSQL
    op.execute("ALTER TYPE kbarticlestatus ADD VALUE IF NOT EXISTS 'APPROVED'")
    op.execute("ALTER TYPE kbarticlestatus ADD VALUE IF NOT EXISTS 'REJECTED'")

    visibility_enum = sa.Enum(
        "INTERNAL", "PUBLIC", "PRIVATE_TEAM", "DEPARTMENT", "ORGANIZATION", name="visibilitylevel"
    )
    visibility_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kb_categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["kb_categories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "slug", name="uq_kb_category_slug"),
    )
    op.create_index("ix_kb_category_org", "kb_categories", ["organization_id"], unique=False)
    op.create_table(
        "kb_analytics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["article_id"], ["kb_articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_kb_analytics_article", "kb_analytics", ["article_id"], unique=False)
    op.create_table(
        "kb_article_tags",
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["kb_articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("article_id", "tag_id"),
    )
    op.create_table(
        "kb_article_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("editor_id", sa.UUID(), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("edit_reason", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["article_id"], ["kb_articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["editor_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_kb_version_article", "kb_article_versions", ["article_id"], unique=False)
    op.create_table(
        "kb_attachments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("uploader_id", sa.UUID(), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_url", sa.String(length=1024), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["article_id"], ["kb_articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploader_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "kb_related_articles",
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("related_article_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["kb_articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["related_article_id"], ["kb_articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("article_id", "related_article_id"),
    )
    op.add_column("kb_articles", sa.Column("category_id", sa.UUID(), nullable=True))
    op.add_column("kb_articles", sa.Column("reviewer_id", sa.UUID(), nullable=True))
    op.add_column("kb_articles", sa.Column("slug", sa.String(length=255), nullable=False))
    op.add_column("kb_articles", sa.Column("summary", sa.Text(), nullable=True))
    op.add_column("kb_articles", sa.Column("rendered_html", sa.Text(), nullable=True))
    op.add_column(
        "kb_articles",
        sa.Column(
            "visibility",
            sa.Enum(
                "INTERNAL",
                "PUBLIC",
                "PRIVATE_TEAM",
                "DEPARTMENT",
                "ORGANIZATION",
                name="visibilitylevel",
            ),
            nullable=False,
        ),
    )
    op.add_column("kb_articles", sa.Column("reading_time_minutes", sa.Integer(), nullable=True))
    op.add_column("kb_articles", sa.Column("views", sa.Integer(), nullable=True))
    op.add_column("kb_articles", sa.Column("helpful_count", sa.Integer(), nullable=True))
    op.add_column("kb_articles", sa.Column("not_helpful_count", sa.Integer(), nullable=True))
    op.add_column("kb_articles", sa.Column("published_at", sa.DateTime(), nullable=True))
    op.alter_column("kb_articles", "version", existing_type=sa.INTEGER(), nullable=False)
    op.drop_index(op.f("ix_kb_article_organization"), table_name="kb_articles")
    op.create_index(
        "ix_kb_article_org_status", "kb_articles", ["organization_id", "status"], unique=False
    )
    op.create_unique_constraint("uq_kb_article_slug", "kb_articles", ["organization_id", "slug"])
    op.create_foreign_key(
        None, "kb_articles", "kb_categories", ["category_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "kb_articles", "users", ["reviewer_id"], ["id"], ondelete="SET NULL"
    )
    op.create_unique_constraint(None, "tickets", ["ticket_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tickets", type_="unique")
    op.drop_constraint(None, "kb_articles", type_="foreignkey")
    op.drop_constraint(None, "kb_articles", type_="foreignkey")
    op.drop_constraint("uq_kb_article_slug", "kb_articles", type_="unique")
    op.drop_index("ix_kb_article_org_status", table_name="kb_articles")
    op.create_index(
        op.f("ix_kb_article_organization"), "kb_articles", ["organization_id"], unique=False
    )
    op.alter_column("kb_articles", "version", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("kb_articles", "published_at")
    op.drop_column("kb_articles", "not_helpful_count")
    op.drop_column("kb_articles", "helpful_count")
    op.drop_column("kb_articles", "views")
    op.drop_column("kb_articles", "reading_time_minutes")
    op.drop_column("kb_articles", "visibility")
    op.drop_column("kb_articles", "rendered_html")
    op.drop_column("kb_articles", "summary")
    op.drop_column("kb_articles", "slug")
    op.drop_column("kb_articles", "reviewer_id")
    op.drop_column("kb_articles", "category_id")
    op.drop_table("kb_related_articles")
    op.drop_table("kb_attachments")
    op.drop_index("ix_kb_version_article", table_name="kb_article_versions")
    op.drop_table("kb_article_versions")
    op.drop_table("kb_article_tags")
    op.drop_index("ix_kb_analytics_article", table_name="kb_analytics")
    op.drop_table("kb_analytics")
    op.drop_index("ix_kb_category_org", table_name="kb_categories")
    op.drop_table("kb_categories")
    # ### end Alembic commands ###
