"""add analytics tables

Revision ID: 9fbcd2b47b5a
Revises: 25ce71297f5f
Create Date: 2026-08-05 20:22:17.704964

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9fbcd2b47b5a"
down_revision: Union[str, Sequence[str], None] = "25ce71297f5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("total_tickets", sa.Integer(), nullable=True),
        sa.Column("open_tickets", sa.Integer(), nullable=True),
        sa.Column("resolved_tickets", sa.Integer(), nullable=True),
        sa.Column("avg_first_response_time_minutes", sa.Integer(), nullable=True),
        sa.Column("avg_resolution_time_minutes", sa.Integer(), nullable=True),
        sa.Column("sla_compliance_percent", sa.Integer(), nullable=True),
        sa.Column("csat_score", sa.Integer(), nullable=True),
        sa.Column("ai_resolution_rate_percent", sa.Integer(), nullable=True),
        sa.Column("automation_success_rate_percent", sa.Integer(), nullable=True),
        sa.Column("knowledge_articles_used", sa.Integer(), nullable=True),
        sa.Column(
            "metrics_json",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "date", name="uq_analytics_snapshot_org_date"),
    )
    op.create_index(
        "ix_analytics_snapshot_org_date",
        "analytics_snapshots",
        ["organization_id", "date"],
        unique=False,
    )
    op.create_table(
        "dashboard_caches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("cache_key", sa.String(length=255), nullable=False),
        sa.Column(
            "payload_json",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "cache_key", name="uq_dashboard_cache_org_key"),
    )
    op.create_index("ix_dashboard_cache_expires", "dashboard_caches", ["expires_at"], unique=False)
    op.create_table(
        "kpi_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column("kpi_name", sa.String(length=100), nullable=False),
        sa.Column("kpi_value", sa.String(length=255), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_kpi_history_org_date", "kpi_history", ["organization_id", "date"], unique=False
    )
    op.create_index(
        "ix_kpi_history_org_target",
        "kpi_history",
        ["organization_id", "target_type", "target_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_kpi_history_org_target", table_name="kpi_history")
    op.drop_index("ix_kpi_history_org_date", table_name="kpi_history")
    op.drop_table("kpi_history")
    op.drop_index("ix_dashboard_cache_expires", table_name="dashboard_caches")
    op.drop_table("dashboard_caches")
    op.drop_index("ix_analytics_snapshot_org_date", table_name="analytics_snapshots")
    op.drop_table("analytics_snapshots")
    # ### end Alembic commands ###
