"""Add CUSTOMER to UserRole

Revision ID: bebeb1f3ef90
Revises: d9a7b5d213b5
Create Date: 2026-08-05 22:20:26.900250

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bebeb1f3ef90"
down_revision: Union[str, Sequence[str], None] = "d9a7b5d213b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userrole ADD VALUE 'CUSTOMER'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
