"""add_rbac_tables

Revision ID: e4bead1f74b7
Revises: 35c2593f1959
Create Date: 2026-08-03 00:54:14.961066

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e4bead1f74b7"
down_revision: Union[str, Sequence[str], None] = "35c2593f1959"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("codename", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("module", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codename"),
    )
    op.create_index("ix_permission_codename", "permissions", ["codename"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_role_org_name"),
    )
    op.create_index("ix_role_organization", "roles", ["organization_id"], unique=False)
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_codename", sa.String(length=100), nullable=False),
        sa.Column("granted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["permission_codename"], ["permissions.codename"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_codename"),
    )
    op.create_table(
        "user_role_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("assigned_by_id", sa.UUID(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["assigned_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "organization_id", name="uq_user_org_role_assignment"),
    )
    op.create_index(
        "ix_role_assignment_org", "user_role_assignments", ["organization_id"], unique=False
    )
    op.create_index("ix_role_assignment_user", "user_role_assignments", ["user_id"], unique=False)
    # ### end Alembic commands ###

    # ### Data Seeding & Enum Update ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("COMMIT")
        op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'PERMISSION_GRANTED'")
        op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'PERMISSION_REVOKED'")
        op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'ROLE_CREATED'")
        op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'ROLE_ASSIGNED'")
        op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'ROLE_REMOVED'")
        op.execute("BEGIN")

    from src.core.permissions import PERMISSION_REGISTRY, DEFAULT_ROLE_PERMISSIONS
    from src.models import UserRole
    import uuid
    from datetime import datetime

    permissions_table = sa.table(
        "permissions",
        sa.column("id", sa.UUID),
        sa.column("codename", sa.String),
        sa.column("display_name", sa.String),
        sa.column("description", sa.Text),
        sa.column("module", sa.String),
        sa.column("created_at", sa.DateTime),
    )

    op.bulk_insert(
        permissions_table,
        [
            {
                "id": uuid.uuid4(),
                "codename": p.codename,
                "display_name": p.display_name,
                "description": p.description,
                "module": p.module,
                "created_at": datetime.utcnow(),
            }
            for p in PERMISSION_REGISTRY
        ],
    )

    roles_table = sa.table(
        "roles",
        sa.column("id", sa.UUID),
        sa.column("organization_id", sa.UUID),
        sa.column("name", sa.String),
        sa.column("description", sa.Text),
        sa.column("is_system", sa.Boolean),
        sa.column("is_custom", sa.Boolean),
        sa.column("created_at", sa.DateTime),
        sa.column("updated_at", sa.DateTime),
    )

    system_roles = []
    role_id_map = {}
    for role_enum in [UserRole.OWNER, UserRole.ADMIN, UserRole.AGENT]:
        role_id = uuid.uuid4()
        role_id_map[role_enum.value] = role_id
        system_roles.append(
            {
                "id": role_id,
                "organization_id": None,
                "name": role_enum.value,
                "description": f"System {role_enum.value} role",
                "is_system": True,
                "is_custom": False,
                "created_at": datetime.utcnow(),
                "updated_at": datetime.utcnow(),
            }
        )

    op.bulk_insert(roles_table, system_roles)

    role_permissions_table = sa.table(
        "role_permissions",
        sa.column("role_id", sa.UUID),
        sa.column("permission_codename", sa.String),
        sa.column("granted_at", sa.DateTime),
    )

    role_permissions = []
    for role_enum, codenames in DEFAULT_ROLE_PERMISSIONS.items():
        role_id = role_id_map[role_enum.value]
        for codename in codenames:
            role_permissions.append(
                {
                    "role_id": role_id,
                    "permission_codename": codename,
                    "granted_at": datetime.utcnow(),
                }
            )

    op.bulk_insert(role_permissions_table, role_permissions)

    users = bind.execute(sa.text("SELECT id, organization_id, role FROM users")).fetchall()

    if users:
        user_role_assignments_table = sa.table(
            "user_role_assignments",
            sa.column("id", sa.UUID),
            sa.column("user_id", sa.UUID),
            sa.column("organization_id", sa.UUID),
            sa.column("role_id", sa.UUID),
            sa.column("assigned_by_id", sa.UUID),
            sa.column("assigned_at", sa.DateTime),
        )

        assignments = []
        for user in users:
            role_value = user.role
            role_id = role_id_map.get(role_value)

            if role_id:
                assignments.append(
                    {
                        "id": uuid.uuid4(),
                        "user_id": user.id,
                        "organization_id": user.organization_id,
                        "role_id": role_id,
                        "assigned_by_id": None,
                        "assigned_at": datetime.utcnow(),
                    }
                )

        if assignments:
            op.bulk_insert(user_role_assignments_table, assignments)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_role_assignment_user", table_name="user_role_assignments")
    op.drop_index("ix_role_assignment_org", table_name="user_role_assignments")
    op.drop_table("user_role_assignments")
    op.drop_table("role_permissions")
    op.drop_index("ix_role_organization", table_name="roles")
    op.drop_table("roles")
    op.drop_index("ix_permission_codename", table_name="permissions")
    op.drop_table("permissions")
    # ### end Alembic commands ###
