"""
Test suite for the Enterprise Ticket Management Engine (SPEC-009).
Covers: lifecycle, state machine, permissions, bulk operations, merge.
"""
import uuid

from fastapi.testclient import TestClient


# ─────────────────────────────────────────────────────────────────────────────
# Test Helpers
# ─────────────────────────────────────────────────────────────────────────────


def _signup_and_login(client: TestClient, email: str, org_name: str) -> dict:
    """Signup as OWNER and return {access_token, org_id, user_id}."""
    resp = client.post(
        "/api/v1/auth/signup",
        json={
            "organization_name": org_name,
            "industry": "Technology",
            "first_name": "Test",
            "last_name": "User",
            "email": email,
            "password": "Password123!",
        },
    )
    assert resp.status_code == 201, resp.text
    token = resp.json()["data"]["access_token"]

    # Fetch user profile to get org_id and user_id
    me_resp = client.get("/api/v1/auth/me", headers={"Authorization": f"Bearer {token}"})
    assert me_resp.status_code == 200, me_resp.text
    me = me_resp.json()["data"]
    return {
        "access_token": token,
        "org_id": me["organization_id"],
        "user_id": me["id"],
    }


def _auth(token: str) -> dict:
    return {"Authorization": f"Bearer {token}"}


def _create_customer(client: TestClient, token: str, email: str = "customer@test.com") -> dict:
    resp = client.post(
        "/api/v1/customers",
        json={"email": email, "name": "Test Customer"},
        headers=_auth(token),
    )
    assert resp.status_code == 201, resp.text
    return resp.json()


def _create_ticket(
    client: TestClient,
    token: str,
    customer_id: str,
    subject: str = "My first ticket",
) -> dict:
    resp = client.post(
        "/api/v1/tickets",
        json={
            "subject": subject,
            "body": "I need help with my order.",
            "customer_id": customer_id,
            "ticket_number": "",  # Will be auto-generated by API
        },
        headers=_auth(token),
    )
    assert resp.status_code == 201, resp.text
    return resp.json()


# ─────────────────────────────────────────────────────────────────────────────
# Customer Tests
# ─────────────────────────────────────────────────────────────────────────────


class TestCustomerCRUD:
    def test_create_customer(self, client: TestClient):
        auth = _signup_and_login(client, "owner_cust@co.com", "Cust Org")
        token = auth["access_token"]
        customer = _create_customer(client, token, "cust1@email.com")
        assert customer["email"] == "cust1@email.com"
        assert "id" in customer

    def test_list_customers(self, client: TestClient):
        auth = _signup_and_login(client, "owner_list@co.com", "ListCust Org")
        token = auth["access_token"]
        _create_customer(client, token, "c1@test.com")
        _create_customer(client, token, "c2@test.com")
        resp = client.get("/api/v1/customers", headers=_auth(token))
        assert resp.status_code == 200
        body = resp.json()
        assert body["total"] >= 2

    def test_get_customer_404(self, client: TestClient):
        auth = _signup_and_login(client, "owner_404@co.com", "404 Org")
        token = auth["access_token"]
        resp = client.get(f"/api/v1/customers/{uuid.uuid4()}", headers=_auth(token))
        assert resp.status_code == 404

    def test_update_customer(self, client: TestClient):
        auth = _signup_and_login(client, "owner_upd@co.com", "Upd Org")
        token = auth["access_token"]
        customer = _create_customer(client, token, "upd@test.com")
        resp = client.patch(
            f"/api/v1/customers/{customer['id']}",
            json={"company": "Acme Corp"},
            headers=_auth(token),
        )
        assert resp.status_code == 200
        assert resp.json()["company"] == "Acme Corp"


# ─────────────────────────────────────────────────────────────────────────────
# Ticket CRUD Tests
# ─────────────────────────────────────────────────────────────────────────────


class TestTicketCRUD:
    def test_create_ticket(self, client: TestClient):
        auth = _signup_and_login(client, "t_create@co.com", "TicketCreate Org")
        token = auth["access_token"]
        customer = _create_customer(client, token)
        ticket = _create_ticket(client, token, customer["id"])

        assert "id" in ticket
        assert "ticket_number" in ticket
        assert ticket["ticket_number"].startswith("SUP-")
        assert ticket["status"] == "NEW"
        assert ticket["priority"] == "MEDIUM"

    def test_list_tickets(self, client: TestClient):
        auth = _signup_and_login(client, "t_list@co.com", "TicketList Org")
        token = auth["access_token"]
        customer = _create_customer(client, token)
        _create_ticket(client, token, customer["id"], "Ticket 1")
        _create_ticket(client, token, customer["id"], "Ticket 2")

        resp = client.get("/api/v1/tickets", headers=_auth(token))
        assert resp.status_code == 200
        body = resp.json()
        assert body["total"] >= 2

    def test_get_ticket_detail(self, client: TestClient):
        auth = _signup_and_login(client, "t_detail@co.com", "Detail Org")
        token = auth["access_token"]
        customer = _create_customer(client, token)
        ticket = _create_ticket(client, token, customer["id"])
        tid = ticket["id"]

        resp = client.get(f"/api/v1/tickets/{tid}", headers=_auth(token))
        assert resp.status_code == 200
        data = resp.json()
        assert data["id"] == tid
        # Should include threads
        assert "threads" in data

    def test_get_ticket_404(self, client: TestClient):
        auth = _signup_and_login(client, "t_404@co.com", "T404 Org")
        token = auth["access_token"]
        resp = client.get(f"/api/v1/tickets/{uuid.uuid4()}", headers=_auth(token))
        assert resp.status_code == 404

    def test_search_by_subject(self, client: TestClient):
        auth = _signup_and_login(client, "t_search@co.com", "TSearch Org")
        token = auth["access_token"]
        customer = _create_customer(client, token)
        _create_ticket(client, token, customer["id"], "Billing issue with invoice")
        _create_ticket(client, token, customer["id"], "Completely different topic")

        resp = client.get("/api/v1/tickets?q=Billing", headers=_auth(token))
        assert resp.status_code == 200
        body = resp.json()
        assert body["total"] == 1
        assert "Billing" in body["items"][0]["subject"]

    def test_delete_ticket(self, client: TestClient):
        auth = _signup_and_login(client, "t_del@co.com", "TDel Org")
        token = auth["access_token"]
        customer = _create_customer(client, token)
        ticket = _create_ticket(client, token, customer["id"])
        tid = ticket["id"]

        resp = client.delete(f"/api/v1/tickets/{tid}", headers=_auth(token))
        assert resp.status_code == 204

        # Should be gone
        resp = client.get(f"/api/v1/tickets/{tid}", headers=_auth(token))
        assert resp.status_code == 404


# ─────────────────────────────────────────────────────────────────────────────
# Lifecycle: Assign, Reply, Status
# ─────────────────────────────────────────────────────────────────────────────


class TestTicketLifecycle:
    def _setup(self, client: TestClient, email_prefix: str):
        auth = _signup_and_login(client, f"{email_prefix}@co.com", f"{email_prefix} Org")
        token = auth["access_token"]
        customer = _create_customer(client, token)
        ticket = _create_ticket(client, token, customer["id"])
        return token, ticket

    def test_assign_ticket(self, client: TestClient):
        token, ticket = self._setup(client, "t_assign")
        auth = _signup_and_login(client, "t_assign2@co.com", "t_assign2 Org")
        # Self-assign
        resp = client.post(
            f"/api/v1/tickets/{ticket['id']}/assign",
            json={"assigned_user_id": None, "assigned_team_id": None},
            headers=_auth(token),
        )
        assert resp.status_code == 200

    def test_assign_transitions_to_assigned(self, client: TestClient):
        auth = _signup_and_login(client, "t_trans@co.com", "Trans Org")
        token = auth["access_token"]
        customer = _create_customer(client, token, "trans_cust@test.com")
        ticket = _create_ticket(client, token, customer["id"])
        user_id = auth["user_id"]

        resp = client.post(
            f"/api/v1/tickets/{ticket['id']}/assign",
            json={"assigned_user_id": user_id},
            headers=_auth(token),
        )
        assert resp.status_code == 200
        assert resp.json()["status"] == "ASSIGNED"

    def test_reply_to_ticket(self, client: TestClient):
        token, ticket = self._setup(client, "t_reply")
        resp = client.post(
            f"/api/v1/tickets/{ticket['id']}/reply",
            json={"body": "We are looking into this.", "is_internal": False},
            headers=_auth(token),
        )
        assert resp.status_code == 200

    def test_internal_note(self, client: TestClient):
        token, ticket = self._setup(client, "t_note")
        resp = client.post(
            f"/api/v1/tickets/{ticket['id']}/reply",
            json={"body": "Internal only note.", "is_internal": True},
            headers=_auth(token),
        )
        assert resp.status_code == 200

    def test_get_thread_includes_notes(self, client: TestClient):
        token, ticket = self._setup(client, "t_thread")
        client.post(
            f"/api/v1/tickets/{ticket['id']}/reply",
            json={"body": "Agent reply", "is_internal": False},
            headers=_auth(token),
        )
        client.post(
            f"/api/v1/tickets/{ticket['id']}/reply",
            json={"body": "Internal note", "is_internal": True},
            headers=_auth(token),
        )
        resp = client.get(
            f"/api/v1/tickets/{ticket['id']}/thread?include_internal=true",
            headers=_auth(token),
        )
        assert resp.status_code == 200
        items = resp.json()
        # 3 items: original body + agent reply + internal note
        assert len(items) >= 2

    def test_get_thread_excludes_notes(self, client: TestClient):
        token, ticket = self._setup(client, "t_thread_excl")
        client.post(
            f"/api/v1/tickets/{ticket['id']}/reply",
            json={"body": "Internal only", "is_internal": True},
            headers=_auth(token),
        )
        resp = client.get(
            f"/api/v1/tickets/{ticket['id']}/thread?include_internal=false",
            headers=_auth(token),
        )
        assert resp.status_code == 200
        items = resp.json()
        # Internal notes should be excluded
        for item in items:
            assert item["thread_type"] != "INTERNAL_NOTE"


# ─────────────────────────────────────────────────────────────────────────────
# State Machine Tests
# ─────────────────────────────────────────────────────────────────────────────


class TestTicketStateMachine:
    def _setup(self, client: TestClient, email_prefix: str):
        auth = _signup_and_login(client, f"{email_prefix}@co.com", f"{email_prefix} Org")
        token = auth["access_token"]
        customer = _create_customer(client, token)
        ticket = _create_ticket(client, token, customer["id"])
        return token, ticket

    def test_new_to_open_valid(self, client: TestClient):
        token, ticket = self._setup(client, "sm_nto")
        resp = client.post(
            f"/api/v1/tickets/{ticket['id']}/status",
            json={"status": "OPEN"},
            headers=_auth(token),
        )
        assert resp.status_code == 200
        assert resp.json()["status"] == "OPEN"

    def test_new_to_closed_invalid(self, client: TestClient):
        token, ticket = self._setup(client, "sm_ntc")
        resp = client.post(
            f"/api/v1/tickets/{ticket['id']}/status",
            json={"status": "CLOSED"},
            headers=_auth(token),
        )
        # Invalid transition — expects 422
        assert resp.status_code == 422

    def test_resolved_to_closed_valid(self, client: TestClient):
        token, ticket = self._setup(client, "sm_rtc")
        # NEW → OPEN → RESOLVED → CLOSED
        tid = ticket["id"]
        client.post(f"/api/v1/tickets/{tid}/status", json={"status": "OPEN"}, headers=_auth(token))
        client.post(f"/api/v1/tickets/{tid}/status", json={"status": "RESOLVED"}, headers=_auth(token))
        resp = client.post(
            f"/api/v1/tickets/{tid}/status", json={"status": "CLOSED"}, headers=_auth(token)
        )
        assert resp.status_code == 200
        assert resp.json()["status"] == "CLOSED"

    def test_cancelled_is_terminal(self, client: TestClient):
        token, ticket = self._setup(client, "sm_cancel")
        tid = ticket["id"]
        client.post(f"/api/v1/tickets/{tid}/status", json={"status": "CANCELLED"}, headers=_auth(token))
        resp = client.post(
            f"/api/v1/tickets/{tid}/status", json={"status": "OPEN"}, headers=_auth(token)
        )
        assert resp.status_code == 422

    def test_resolved_sets_resolved_at(self, client: TestClient):
        token, ticket = self._setup(client, "sm_rsat")
        tid = ticket["id"]
        client.post(f"/api/v1/tickets/{tid}/status", json={"status": "OPEN"}, headers=_auth(token))
        resp = client.post(
            f"/api/v1/tickets/{tid}/status", json={"status": "RESOLVED"}, headers=_auth(token)
        )
        assert resp.status_code == 200
        assert resp.json()["resolved_at"] is not None

    def test_closed_sets_closed_at(self, client: TestClient):
        token, ticket = self._setup(client, "sm_csat")
        tid = ticket["id"]
        client.post(f"/api/v1/tickets/{tid}/status", json={"status": "OPEN"}, headers=_auth(token))
        client.post(f"/api/v1/tickets/{tid}/status", json={"status": "RESOLVED"}, headers=_auth(token))
        resp = client.post(
            f"/api/v1/tickets/{tid}/status", json={"status": "CLOSED"}, headers=_auth(token)
        )
        assert resp.status_code == 200
        assert resp.json()["closed_at"] is not None


# ─────────────────────────────────────────────────────────────────────────────
# Merge Tests
# ─────────────────────────────────────────────────────────────────────────────


class TestTicketMerge:
    def test_merge_tickets(self, client: TestClient):
        auth = _signup_and_login(client, "t_merge@co.com", "Merge Org")
        token = auth["access_token"]
        customer = _create_customer(client, token, "merge_cust@test.com")

        t1 = _create_ticket(client, token, customer["id"], "Source ticket")
        t2 = _create_ticket(client, token, customer["id"], "Target ticket")

        resp = client.post(
            f"/api/v1/tickets/merge?source_ticket_id={t1['id']}",
            json={"target_ticket_id": t2["id"]},
            headers=_auth(token),
        )
        assert resp.status_code == 200
        # Returns the target ticket
        assert resp.json()["id"] == t2["id"]

    def test_merge_soft_deletes_source(self, client: TestClient):
        auth = _signup_and_login(client, "t_merge2@co.com", "Merge2 Org")
        token = auth["access_token"]
        customer = _create_customer(client, token, "merge2_cust@test.com")

        t1 = _create_ticket(client, token, customer["id"], "Source2")
        t2 = _create_ticket(client, token, customer["id"], "Target2")

        client.post(
            f"/api/v1/tickets/merge?source_ticket_id={t1['id']}",
            json={"target_ticket_id": t2["id"]},
            headers=_auth(token),
        )
        # Source should be gone (soft-deleted)
        resp = client.get(f"/api/v1/tickets/{t1['id']}", headers=_auth(token))
        assert resp.status_code == 404

    def test_cannot_merge_with_itself(self, client: TestClient):
        auth = _signup_and_login(client, "t_merge3@co.com", "Merge3 Org")
        token = auth["access_token"]
        customer = _create_customer(client, token, "merge3_cust@test.com")
        t1 = _create_ticket(client, token, customer["id"], "Self merge")

        resp = client.post(
            f"/api/v1/tickets/merge?source_ticket_id={t1['id']}",
            json={"target_ticket_id": t1["id"]},
            headers=_auth(token),
        )
        assert resp.status_code == 422


# ─────────────────────────────────────────────────────────────────────────────
# Bulk Operation Tests
# ─────────────────────────────────────────────────────────────────────────────


class TestBulkOperations:
    def test_bulk_assign(self, client: TestClient):
        auth = _signup_and_login(client, "t_bulk@co.com", "Bulk Org")
        token = auth["access_token"]
        customer = _create_customer(client, token, "bulk_cust@test.com")

        t1 = _create_ticket(client, token, customer["id"], "Bulk T1")
        t2 = _create_ticket(client, token, customer["id"], "Bulk T2")

        resp = client.post(
            "/api/v1/tickets/bulk/assign",
            json={
                "ticket_ids": [t1["id"], t2["id"]],
                "assigned_user_id": auth["user_id"],
            },
            headers=_auth(token),
        )
        assert resp.status_code == 200
        results = resp.json()["results"]
        assert len(results) == 2
        assert all(r["success"] for r in results)

    def test_bulk_status_update(self, client: TestClient):
        auth = _signup_and_login(client, "t_bulk_s@co.com", "BulkS Org")
        token = auth["access_token"]
        customer = _create_customer(client, token, "bulks_cust@test.com")

        t1 = _create_ticket(client, token, customer["id"], "BulkS T1")
        t2 = _create_ticket(client, token, customer["id"], "BulkS T2")

        resp = client.post(
            "/api/v1/tickets/bulk/status",
            json={"ticket_ids": [t1["id"], t2["id"]], "status": "OPEN"},
            headers=_auth(token),
        )
        assert resp.status_code == 200
        results = resp.json()["results"]
        assert all(r["success"] for r in results)
        assert all(r["new_status"] == "OPEN" for r in results)

    def test_bulk_invalid_transition_partial_failure(self, client: TestClient):
        """Bulk operations report failures per-ticket without aborting the batch."""
        auth = _signup_and_login(client, "t_bulk_f@co.com", "BulkF Org")
        token = auth["access_token"]
        customer = _create_customer(client, token, "bulkf_cust@test.com")

        t1 = _create_ticket(client, token, customer["id"], "Good ticket")
        t2 = _create_ticket(client, token, customer["id"], "Good ticket 2")
        # Move t2 to CANCELLED (terminal)
        client.post(
            f"/api/v1/tickets/{t2['id']}/status",
            json={"status": "CANCELLED"},
            headers=_auth(token),
        )

        # Try to bulk-move both to OPEN; t1 should succeed, t2 should fail
        resp = client.post(
            "/api/v1/tickets/bulk/status",
            json={"ticket_ids": [t1["id"], t2["id"]], "status": "OPEN"},
            headers=_auth(token),
        )
        if resp.status_code != 200:
            print("ERROR BODY:", resp.json())
        assert resp.status_code == 200
        results = resp.json()["results"]
        successes = [r for r in results if r["success"]]
        failures = [r for r in results if not r["success"]]
        assert len(successes) >= 1
        assert len(failures) >= 1
